// Generated by squad init/upgrade -- do not edit
// -- zero dependencies --
//
// Standalone token resolution for agent identity.
// Uses only Node.js built-in modules -- no npm dependencies required.
//
// Usage: node .squad/scripts/resolve-token.mjs [--required] <role_slug>
// Output: installation access token on stdout, or empty stdout on failure (exit 0).
//         With --required: exits 1 if token could not be resolved.

import { createSign, createPrivateKey } from 'node:crypto';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// ============================================================================
// Role aliases -- generic only (no character names)
// ============================================================================

const ROLE_ALIASES = {
  core: 'backend',
  ui: 'frontend',
  qa: 'tester',
  ops: 'devops',
  writer: 'docs',
  sec: 'security',
  ml: 'data',
  note: 'scribe',
};

export function resolveRoleSlug(slug) {
  return ROLE_ALIASES[slug] ?? slug;
}

// ============================================================================
// Base64url helpers
// ============================================================================

function base64url(input) {
  const b64 = Buffer.from(input).toString('base64');
  return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

// ============================================================================
// Credential loading
// ============================================================================

function loadAppRegistration(projectRoot, key) {
  const regPath = join(projectRoot, '.squad', 'identity', 'apps', `${key}.json`);
  try {
    const raw = readFileSync(regPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

// ============================================================================
// JWT generation
// ============================================================================

// Internal sync JWT builder. resolveTokenWithDiagnostics calls this directly so
// getInstallationToken is registered synchronously (required for fake timer tests).
function buildJWT(appId, privateKeyPem, nowOverride) {
  try {
    createPrivateKey(privateKeyPem);
  } catch (e) {
    throw new Error('Invalid PEM format: ' + e.message);
  }
  const now = nowOverride !== undefined ? nowOverride : Math.floor(Date.now() / 1000);
  const header = { alg: 'RS256', typ: 'JWT' };
  const payload = { iss: appId, iat: now - 60, exp: now + 540 };
  const encodedHeader = base64url(JSON.stringify(header));
  const encodedPayload = base64url(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;
  const signer = createSign('RSA-SHA256');
  signer.update(signingInput);
  signer.end();
  const encodedSignature = base64url(signer.sign(privateKeyPem));
  return `${signingInput}.${encodedSignature}`;
}

/**
 * Generate a JWT for GitHub App authentication (RS256, 9 min TTL).
 * Validates PEM via createPrivateKey; returns rejected Promise on invalid key.
 * @param {number} appId
 * @param {string} privateKeyPem
 * @param {number} [nowOverride]
 * @returns {Promise<string>}
 */
export async function generateAppJWT(appId, privateKeyPem, nowOverride) {
  return buildJWT(appId, privateKeyPem, nowOverride);
}

// ============================================================================
// Installation token exchange
// ============================================================================

async function getInstallationToken(jwt, installationId) {
  const url = `https://api.github.com/app/installations/${installationId}/access_tokens`;
  const controller = new AbortController();
  const timer = setTimeout(function () { controller.abort(); }, 10_000);
  const timeoutPromise = new Promise(function (_, reject) {
    controller.signal.addEventListener('abort', function () {
      reject(new Error('fetch timeout: installation token request exceeded 10s'));
    });
  });
  let response;
  try {
    response = await Promise.race([
      fetch(url, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${jwt}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        signal: controller.signal,
      }),
      timeoutPromise,
    ]);
  } finally {
    clearTimeout(timer);
  }
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`GitHub API error ${response.status} creating installation token: ${body}`);
  }
  const data = await response.json();
  return { token: data.token, expiresAt: new Date(data.expires_at) };
}

// ============================================================================
// Environment variable credential resolution
// ============================================================================

function resolveEnvCredentials(roleKey) {
  const envKey = roleKey.toUpperCase();
  const appIdStr = process.env[`SQUAD_${envKey}_APP_ID`];
  const pemRaw = process.env[`SQUAD_${envKey}_PRIVATE_KEY`];
  const installIdStr = process.env[`SQUAD_${envKey}_INSTALLATION_ID`];
  const setCount = [appIdStr, pemRaw, installIdStr].filter(Boolean).length;
  if (setCount === 0) return { credentials: null, error: null };
  if (setCount < 3) {
    const missing = [
      !appIdStr && `SQUAD_${envKey}_APP_ID`,
      !pemRaw && `SQUAD_${envKey}_PRIVATE_KEY`,
      !installIdStr && `SQUAD_${envKey}_INSTALLATION_ID`,
    ].filter(Boolean);
    return { credentials: null, error: `Partial env config for role '${roleKey}': missing ${missing.join(', ')}` };
  }
  const appId = Number(appIdStr);
  const installationId = Number(installIdStr);
  if (!Number.isFinite(appId) || !Number.isFinite(installationId)) return { credentials: null, error: null };
  const pem = pemRaw.trimStart().startsWith('-----BEGIN') ? pemRaw : Buffer.from(pemRaw, 'base64').toString('utf-8');
  return { credentials: { appId, pem, installationId }, error: null };
}

// ============================================================================
// Token cache (in-process, keyed by projectRoot:roleKey)
// ============================================================================

const tokenCache = new Map();
const REFRESH_MARGIN_MS = 10 * 60 * 1000;

/** Clear the in-process token cache (useful for testing). */
export function clearTokenCache() { tokenCache.clear(); }

// ============================================================================
// High-level token resolution with diagnostics
// ============================================================================

export async function resolveTokenWithDiagnostics(projectRoot, roleKey) {
  const resolvedRoleKey = resolveRoleSlug(roleKey);
  if (process.env['SQUAD_IDENTITY_MOCK'] === '1') {
    const mockToken = process.env['SQUAD_IDENTITY_MOCK_TOKEN'] || (`mock-token-${resolvedRoleKey}`);
    return { token: mockToken, resolvedRoleKey, error: null };
  }
  const cacheKey = `${projectRoot}:${resolvedRoleKey}`;
  const cached = tokenCache.get(cacheKey);
  if (cached) {
    const remainingMs = cached.expiresAt.getTime() - Date.now();
    if (remainingMs > REFRESH_MARGIN_MS) return { token: cached.token, resolvedRoleKey, error: null };
    tokenCache.delete(cacheKey);
  }
  const { credentials: envCreds, error: envError } = resolveEnvCredentials(resolvedRoleKey);
  if (envError) {
    process.stderr.write(`[squad] identity: ${envError}\n`);
    return { token: null, resolvedRoleKey: null, error: { kind: 'runtime', message: envError } };
  }
  if (envCreds) {
    try {
      const jwt = buildJWT(envCreds.appId, envCreds.pem);
      const { token, expiresAt } = await getInstallationToken(jwt, envCreds.installationId);
      tokenCache.set(cacheKey, { token, expiresAt });
      return { token, resolvedRoleKey, error: null };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      process.stderr.write(`[squad] identity: env-based token resolution failed: ${message}\n`);
      return { token: null, resolvedRoleKey: null, error: { kind: 'runtime', message } };
    }
  }
  const reg = loadAppRegistration(projectRoot, resolvedRoleKey);
  if (!reg || !reg.installationId) {
    return { token: null, resolvedRoleKey: null, error: { kind: 'not-configured', message: `No registration found for role '${resolvedRoleKey}'` } };
  }
  const pemPath = join(projectRoot, '.squad', 'identity', 'keys', `${resolvedRoleKey}.pem`);
  if (!existsSync(pemPath)) {
    return { token: null, resolvedRoleKey: null, error: { kind: 'not-configured', message: `PEM key not found: ${pemPath}` } };
  }
  try {
    const mode = statSync(pemPath).mode;
    if (mode & 0o044) {
      process.stderr.write(`[squad] warning: PEM file ${pemPath} is readable by group/others (mode ${(mode & 0o777).toString(8)})\n`);
    }
  } catch (_) { /* ignore stat errors */ }
  const pem = readFileSync(pemPath, 'utf-8');
  try {
    const jwt = buildJWT(reg.appId, pem);
    const { token, expiresAt } = await getInstallationToken(jwt, reg.installationId);
    tokenCache.set(cacheKey, { token, expiresAt });
    return { token, resolvedRoleKey, error: null };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`[squad] identity: filesystem-based token resolution failed: ${message}\n`);
    return { token: null, resolvedRoleKey: null, error: { kind: 'runtime', message } };
  }
}

/**
 * Backward-compatible wrapper around resolveTokenWithDiagnostics -- returns null on any error.
 */
export async function resolveToken(projectRoot, roleKey) {
  const { token } = await resolveTokenWithDiagnostics(projectRoot, roleKey);
  return token;
}

// ============================================================================
// CLI entry point
// ============================================================================

function parseCliArgs(argv) {
  const args = argv.slice(2);
  const required = args.includes('--required');
  const roleSlug = args.find(function (a) { return !a.startsWith('-'); });
  return { roleSlug, required };
}

/** True when this file is being run directly as a script (not imported). */
export const isCliInvocation = (function () {
  try {
    return process.argv[1] === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}());

if (isCliInvocation) {
  const { roleSlug, required } = parseCliArgs(process.argv);
  if (!roleSlug) process.exit(0);

  // Derive project root from script location (.squad/scripts/ --> repo root).
  let projectRoot = process.cwd();
  try {
    const scriptDir = dirname(fileURLToPath(import.meta.url));
    projectRoot = join(scriptDir, '..', '..');
  } catch (_) { /* fallback to cwd */ }

  const { token, error } = await resolveTokenWithDiagnostics(projectRoot, roleSlug);

  if (token) {
    process.stdout.write(token);
    process.exit(0);
  }

  if (required) {
    const msg = (error && error.message) || (`Could not resolve token for role '${roleSlug}'`);
    process.stderr.write(`[squad] error: ${msg}\n`);
    process.exit(1);
  }

  process.exit(0);
}
